name: Update Icons

on:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  update:
    name: Update Icons

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: "chore: update icons"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}